# Generated by Django 2.1.2 on 2019-01-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bloqueados',
            field=models.ManyToManyField(related_name='contatos_bloqueados', to='perfis.Perfil'),
        ),
    ]
